repos:
  - repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
      - id: black

  # - repo: https://github.com/PyCQA/flake8
  #   rev: 7.0.0
  #   hooks:
  #     - id: flake8
  
  # - repo: local
  #   hooks:
  #     - id: pytest-staged
  #       name: pytest (staged files)
  #       entry: pytest
  #       language: system
  #       types: [python]
  #       pass_filenames: true   # by this Only runs tests of the staged files

  - repo: local
    hooks:
      - id: pytest-all
        name: pytest (full suite)
        entry: pytest
        language: system
        stages: [pre-push]    #only runs on pre-push
        pass_filenames: false
