# version: "3.9"

services:
  app:
    build: .
    image: ${DOCKERHUB_USERNAME}/url-shortener:latest  # â† add this

    container_name: shortener-api
    # env_file:
    #   - .env      we can skip this so that it will inherit env vars from workflow instead
    ports:
      - "${PORT}:${PORT}"  #maps local PORT to container PORT
    volumes:
      - ./app/db/GeoLite2-City.mmdb:/app/db/GeoLite2-City.mmdb:ro
    environment:
      DATABASE_URI: ${DATABASE_URI}
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM_TO_ENCODE: ${ALGORITHM_TO_ENCODE}
      UPSTASH_REDIS_REST_URL: ${UPSTASH_REDIS_REST_URL}
      UPSTASH_REDIS_REST_TOKEN: ${UPSTASH_REDIS_REST_TOKEN}
      GEOIP_DB_PATH: ${GEOIP_DB_PATH}
      PORT: ${PORT}
    command: >
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port ${PORT}"
