# version: "3.9"

services:
  app:
    build: .
    container_name: shortener-api
    # env_file:
    #   - .env      we can skip this so that it will inherit env vars from workflow instead
    ports:
      - "${PORT}:${PORT}"  #maps local PORT to container PORT
    volumes:
      - ./app/db/GeoLite2-City.mmdb:/app/db/GeoLite2-City.mmdb:ro
    command: >
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port ${PORT}"
