name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      DATABASE_URI: ${{secrets.DATABASE_URI}}
      SECRET_KEY: ${{secrets.SECRET_KEY}}
      ALGORITHM_TO_ENCODE: ${{secrets.ALGORITHM_TO_ENCODE}}
      UPSTASH_REDIS_REST_URL: ${{secrets.UPSTASH_REDIS_REST_URL}}
      UPSTASH_REDIS_REST_TOKEN: ${{secrets.UPSTASH_REDIS_REST_TOKEN}}
      GEOIP_DB_PATH : ${{secrets.GEOIP_DB_PATH}}
      PORT: ${{secrets.PORT}}
      DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
      DOCKERHUB_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      - name: Run pre-commit
        run: pre-commit run --all-files
      
      - name: Log in to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker compose build --no-cache

      - name: Run tests
        run: |
          docker compose run --rm app pytest tests/ --maxfail=1 --disable-warnings -v
      
       # push only if branch is main and tests are passed successfully
      - name: Push image to Docker Hub
        if: github.ref == 'refs/heads/main' && success()
        run: docker compose push

      # - name: Trigger Render deployment
      #   if: github.ref == 'refs/heads/main' && success()
      #   run: |
      #     curl -X POST "https://api.render.com/deploy/${{ secrets.RENDER_SERVICE_ID }}" \
      #       -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"

      - name: Trigger Render deployment
        if: github.ref == 'refs/heads/main' && success()
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"

